---
name: Mirror to GitHub
on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  main:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: mfinelli/fluentd-multi/fluentd-multi
          tag_with_ref: true
      - uses: peter-evans/dockerhub-description@v2
        if: ${{ startsWith(github.ref, 'v') }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mfinelli/fluentd-multi
          short-description: "fluentd-kubernetes-daemonset with multiple plugins"
