---
name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  main:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: bodytext
        run: echo "::set-output name=version::$(sed 's|^refs/tags/v||' <<< "${{ github.ref }}")"
      - uses: ncipollo/release-action@v1
        with:
          body: Version ${{ steps.bodytext.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
      # - uses: peter-evans/dockerhub-description@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     repository: mfinelli/fluentd-multi
      #     short-description: "fluentd-kubernetes-daemonset with multiple plugins"
